### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RiveReactNativeView" was not found in the UIManager

### ISSUE THREAD

**Issue by mourice38** [lklima/rive-animated-app#1]

**Comment by mourice38** [comment]
![rive](https://user-images.githubusercontent.com/94263262/178105555-c856c89f-c927-49f5-b21d-253944b86c56.PNG)

**Comment by lklima** [comment]
Hi @mourice38 you need to run `yarn android` or `npm run android`, I just tested it here, it worked without issues.

<img src="https://user-images.githubusercontent.com/44346970/178125580-9a5909b8-6659-432f-a43a-448ea4ea8ce1.png" width="300">

**Comment by mourice38** [comment]
Thank you for your attention. It's a nice animation. I look forward to the
continuation of your work and sharing it with us. I am trying to improve
myself in reanimated. I would appreciate especially if you share your react
native animation animation sample projects or works or your
recommendations. have a nice day

Lucas Lima ***@***.***>, 10 Tem 2022 Paz, 02:25 tarihinde
şunu yazdı:
